apiVersion: v1
kind: Namespace
metadata:
  name: react-frontend
  labels:
    name: react-frontend
    app.kubernetes.io/name: react-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: kubernetes-platform