apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: react-frontend
  labels:
    app: react-frontend
    component: frontend
spec:
  type: NodePort
  selector:
    app: react-frontend
  ports:
  - name: http
    port: 3000
    targetPort: http
    nodePort: 30080
    protocol: TCP