apiVersion: v1
kind: Service
metadata:
  name: python-api
  namespace: python-api
  labels:
    app: python-api
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: python-api
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP