apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: java-service
  labels:
    app: java-service
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app: java-service
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP